"""add_committed_at_to_commits

Revision ID: 021107dc0f72
Revises: acc0de4340ba
Create Date: 2026-06-15 02:10:46.991212

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '021107dc0f72'
down_revision: str | Sequence[str] | None = 'acc0de4340ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commits', 'committed_at')
    # ### end Alembic commands ###
