"""enterprise schema: add fields, teams, audit log

Revision ID: 22bdfcb83974
Revises: 6590591ee57c
Create Date: 2026-06-10 16:22:55.695265

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22bdfcb83974'
down_revision: str | Sequence[str] | None = '6590591ee57c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.add_column('commits', sa.Column('additions', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('commits', sa.Column('deletions', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('commits', sa.Column('files_changed', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('default_branch', sa.String(length=255), nullable=False, server_default=sa.text("'main'")))
    op.add_column('projects', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('settings', sa.Text(), nullable=False, server_default=sa.text("'{}'")))
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.add_column('reviews', sa.Column('trigger_type', sa.String(length=32), nullable=False, server_default=sa.text("'manual'")))
    op.add_column('reviews', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('files_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('reviews', sa.Column('commits_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('reviews', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=sa.text("''")))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=False, server_default=sa.text("''")))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('team_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'])
    op.add_column('webhook_events', sa.Column('repo_full_name', sa.String(length=512), nullable=False, server_default=sa.text("''")))
    op.add_column('webhook_events', sa.Column('response_status', sa.Integer(), nullable=True))
    op.add_column('webhook_events', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'response_time_ms')
    op.drop_column('webhook_events', 'response_status')
    op.drop_column('webhook_events', 'repo_full_name')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'password_hash')
    op.drop_column('reviews', 'branch')
    op.drop_column('reviews', 'commits_count')
    op.drop_column('reviews', 'files_count')
    op.drop_column('reviews', 'author')
    op.drop_column('reviews', 'trigger_type')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'settings')
    op.drop_column('projects', 'last_activity_at')
    op.drop_column('projects', 'owner_id')
    op.drop_column('projects', 'default_branch')
    op.drop_column('projects', 'description')
    op.drop_column('commits', 'files_changed')
    op.drop_column('commits', 'deletions')
    op.drop_column('commits', 'additions')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('teams')
    # ### end Alembic commands ###
