"""add finding tracking, archive, constraints

Revision ID: 87a19216a4d2
Revises: 2b5bd5b1ab2c
Create Date: 2026-06-10 16:33:04.555551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a19216a4d2'
down_revision: Union[str, Sequence[str], None] = '2b5bd5b1ab2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_resolved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('comments', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('resolved_by', sa.String(length=255), nullable=True))
    # 去重：保留同 project_id+sha 的最新一条记录
    op.execute("""
        DELETE FROM commits
        WHERE id NOT IN (
            SELECT MIN(id) FROM commits GROUP BY project_id, sha
        )
    """)
    op.create_unique_constraint('uq_commit_project_sha', 'commits', ['project_id', 'sha'])
    op.add_column('findings', sa.Column('detected_by', sa.String(length=32), nullable=False, server_default=sa.text("'ai'")))
    op.add_column('findings', sa.Column('is_fixed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('findings', sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('findings', sa.Column('fixed_by', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.execute("""
        DELETE FROM pull_requests
        WHERE id NOT IN (
            SELECT MIN(id) FROM pull_requests GROUP BY project_id, pr_number
        )
    """)
    op.create_unique_constraint('uq_pr_project_number', 'pull_requests', ['project_id', 'pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pr_project_number', 'pull_requests', type_='unique')
    op.drop_column('projects', 'is_archived')
    op.drop_column('findings', 'fixed_by')
    op.drop_column('findings', 'fixed_at')
    op.drop_column('findings', 'is_fixed')
    op.drop_column('findings', 'detected_by')
    op.drop_constraint('uq_commit_project_sha', 'commits', type_='unique')
    op.drop_column('comments', 'resolved_by')
    op.drop_column('comments', 'resolved_at')
    op.drop_column('comments', 'is_resolved')
    # ### end Alembic commands ###
