"""add reviews.error_message

Revision ID: 899e3377030d
Revises: 87a19216a4d2
Create Date: 2026-06-11 15:40:58.444497

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "899e3377030d"
down_revision: str | Sequence[str] | None = "87a19216a4d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("error_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "error_message")
    # ### end Alembic commands ###
