"""add_reviewed_files_and_comment_id

Revision ID: acc0de4340ba
Revises: b2c3d4e5f6a7
Create Date: 2026-06-15 00:44:40.062022

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'acc0de4340ba'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('pr_comment_id', sa.BigInteger(), nullable=True))
    op.add_column('reviews', sa.Column('reviewed_files', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewed_files')
    op.drop_column('pull_requests', 'pr_comment_id')
    # ### end Alembic commands ###
